# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72bd71b18f791bdeaf28df95f850e741c82a2ef1c3536a66da7b89ed018420efa9d8c2dd42dd7520bd1d49a124bc27a823dcd0dfc6f57285cee1003f38c02922

test:
  secret_key_base: 32a6e276de9b7a1dce61a30af290f51a9aee4f380c9a093002ab93abbf00dc62f2e3e62c24b5401e24ea82369f0967c181495caabf58432626e420e4450b6f34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
